[package]
name = "tocc"
version = "0.1.0"
authors = ["TA Thanh Dinh <tathanhdinh@gmail.com>"]
description = "A type-obfuscated C compiler"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cranelift = "0.46.1"
cranelift-faerie = "0.46.1"
cranelift-module = "0.46.1"
cranelift-simplejit = "0.46.1"
libc = "0.2.64"
zydis = "3.0.0"
peg = "0.6.0"
structopt = "0.3.3"
