[package]
name = "cr9cc"
version = "0.1.0"
authors = ["TA Thanh Dinh <tathanhdinh@gmail.com>"]
description = "A type-obfuscated C compiler"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cranelift = "0.45.0"
cranelift-faerie = "0.45.0"
cranelift-module = "0.45.0"
cranelift-simplejit = "0.45.0"
