edition = "2018"
reorder_imports = true
reorder_modules = true
hard_tabs = true
max_width = 100
# fn_single_line = true
fn_args_layout = "Compressed"
# brace_style = "PreferSameLine"
# condense_wildcard_suffixes = true
# indent_style = "Visual"
# imports_indent = "Visual"
# trailing_comma = "Never"
use_field_init_shorthand = true
use_small_heuristics = "Max"
